# Generated by Django 4.1.4 on 2023-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("NumGuest", models.SmallIntegerField()),
                ("BookingDate", models.DateTimeField()),
            ],
        ),
    ]
