# Generated by Django 4.1.4 on 2023-08-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_rename_bookingtable_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="Inventory",
            new_name="inventory",
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="Title",
            new_name="title",
        ),
    ]
